In [ ]:
# kNN -> k = 3; no data preprocessing

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('diabetes_012_health_indicators_BRFSS2015.csv')

In [3]:
# less_data = data[:len(data)//1] #use only 20% of the data
# X = less_data.copy()
# Y = X.pop('Diabetes_012')

In [4]:
X=data.drop(["Diabetes_012"],axis=1)
Y=data["Diabetes_012"]

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.2, random_state=20)

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(202944, 21)
(202944,)
(50736, 21)
(50736,)


In [ ]:
kNN = KNeighborsClassifier(n_neighbors=3) 
kNN.fit(X_train, Y_train) 
Y_pred = kNN.predict(X_test) 

In [8]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, matthews_corrcoef, accuracy_score, f1_score

print("Accuracy score: ", accuracy_score(Y_test, Y_pred)*100)
print("F1_Score: ", f1_score(Y_test, Y_pred, average='weighted')*100) #F1-Score
print ("MCC: ", matthews_corrcoef(Y_test, Y_pred)) # mcc
print("MSE: ", mean_squared_error(Y_test, Y_pred)) #mse
print("MAE: ", mean_absolute_error(Y_test, Y_pred)) #mae
print("\n Classification report \n ", classification_report(Y_test, Y_pred))
print("\n Confusion matrix \n ", confusion_matrix(Y_test, Y_pred))

Accuracy score:  82.24337748344371
F1_Score:  79.85332245532362
MCC:  0.1994794213538706
MSE:  0.6526726584673604
MAE:  0.3359350362661621
Classification report 
                precision    recall  f1-score   support

         0.0       0.87      0.94      0.90     42753
         1.0       0.06      0.00      0.01       927
         2.0       0.37      0.23      0.28      7056

    accuracy                           0.82     50736
   macro avg       0.43      0.39      0.40     50736
weighted avg       0.78      0.82      0.80     50736

Confusion matrix 
  [[40094    40  2619]
 [  787     3   137]
 [ 5416    10  1630]]
