In [ ]:
# kNN-> 3; standard scaler

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('diabetes_012_health_indicators_BRFSS2015.csv')
data.head()

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0           0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1           0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2           0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3           0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4           0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [3]:
#less_data = data[:len(data)//1] #use only 20% of the data

In [4]:
# X = less_data.copy()
# Y = X.pop('Diabetes_012')

In [5]:
X=data.drop(["Diabetes_012"],axis=1)
Y=data["Diabetes_012"]

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.2, random_state=20)

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(202944, 21)
(202944,)
(50736, 21)
(50736,)


In [7]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

for col in X_train.columns:
  X_train[col] = std_scaler.fit_transform(X_train[[col]])

for col in X_test.columns:
  X_test[col] = std_scaler.fit_transform(X_test[[col]])

<ipython-input-7-66f93d97ba6a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = std_scaler.fit_transform(X_train[[col]])
<ipython-input-7-66f93d97ba6a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = std_scaler.fit_transform(X_train[[col]])
<ipython-input-7-66f93d97ba6a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pyda

<ipython-input-7-66f93d97ba6a>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = std_scaler.fit_transform(X_test[[col]])
<ipython-input-7-66f93d97ba6a>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = std_scaler.fit_transform(X_test[[col]])
<ipython-input-7-66f93d97ba6a>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.o

In [8]:
kNN = KNeighborsClassifier(n_neighbors=3) 
kNN.fit(X_train, Y_train) 
Y_pred = kNN.predict(X_test) 

In [9]:
Y_pred

array([0., 0., 0., ..., 0., 2., 2.])

In [10]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, matthews_corrcoef, accuracy_score, f1_score

print("Accuracy score: ", accuracy_score(Y_test, Y_pred)*100)
print("F1_Score: ", f1_score(Y_test, Y_pred, average='weighted')*100) #F1-Score
print ("MCC: ", matthews_corrcoef(Y_test, Y_pred)) # mcc
print("MSE: ", mean_squared_error(Y_test, Y_pred)) #mse
print("MAE: ", mean_absolute_error(Y_test, Y_pred)) #mae
print("\n Classification report \n ", classification_report(Y_test, Y_pred))
print("\n Confusion matrix \n ", confusion_matrix(Y_test, Y_pred))

Accuracy score:  82.08964049195838
F1_Score:  79.85121963349934
MCC:  0.20245518713609248
MSE:  0.6576986754966887
MAE:  0.3386352885525071

 Classification report 
                precision    recall  f1-score   support

         0.0       0.87      0.93      0.90     42753
         1.0       0.03      0.00      0.00       927
         2.0       0.37      0.24      0.29      7056

    accuracy                           0.82     50736
   macro avg       0.42      0.39      0.40     50736
weighted avg       0.78      0.82      0.80     50736


 Confusion matrix 
  [[39958    47  2748]
 [  773     2   152]
 [ 5346    21  1689]]
